language: node_js
node_js:
- '8'
install:
- npm install -g travis-ci-cloudfront-invalidation
- yarn install
before_deploy:
- yarn build
- pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync build $AWS_S3_BUCKET --region=us-west-2 --delete
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
