language: node_js
node_js:
- '8'
install:
- npm install -g travis-ci-cloudfront-invalidation yarn
- yarn install
before_deploy:
- yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET
  acl: public_read
  local_dir: build
  skip_cleanup: true
  region: us-west-2
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
